[package]
name = "rabitq"
version = "0.0.0"
edition = "2024"
rust-version = "1.85"
publish = false

[dependencies]
bytemuck.workspace = true
faer.workspace = true
pulp.workspace = true
rand.workspace = true
rand_distr = "0.5.0"
rayon.workspace = true

[dev-dependencies]
seed-rand = { path = "../seed_rand" }
