[package]
name = "rabitq"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
bytemuck.workspace = true
faer.workspace = true
pulp.workspace = true
rand.workspace = true
rayon.workspace = true

[target.'cfg(any(target_arch = "x86", target_arch = "x86_64"))'.dependencies]
pulp = { workspace = true, features = ["x86-v4"] }

[dev-dependencies]
seed-rand = { path = "../seed_rand" }
